config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  # You can have the root of your site routed with "root"
  resources :loans, only: [:new, :index, :create] do
    member do
<<<<<<< HEAD
      get 'generate_amortization_schedule'
=======
      get 'calculate_amortization_schedule'
>>>>>>> b4be61b0148bdb2901ddfe4f8578c9840eb76389
    end
  end

  root 'loans#new'

end

app/models/loan.rb
<<<<<<< HEAD

=======
>>>>>>> b4be61b0148bdb2901ddfe4f8578c9840eb76389
class Loan < ActiveRecord::Base
  VALID_AMORTIZATION_TYPE = ['Equal payments', 'First month different payment'].freeze
  validates :interest_rate, presence:  true, numericality: { greater_than: 0 },
                            format: { with: /\A\d+(?:\.\d{0,2})?\z/, message: 'format is incorrect(2 decimal point is only allowed)' }
  validates :loan_amount, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :monthly, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  validates :request_date, presence: true
  validates :amortization_type, presence: true,
                                inclusion: { in: VALID_AMORTIZATION_TYPE, message: '%{value} is not a valid amortization type' }
  validate  :request_date_cannot_be_in_the_future

  def amortization_schedule
    AmortizationScheduleGenerator.new(self).perform
  end

  private

  def request_date_cannot_be_in_the_future
    errors.add(:request_date, "Request date can't be in the future") if request_date.present? && (request_date > Date.today)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  def new
    @loan = Loan.new
  end

  def create
    @loan = Loan.new(loan_params)
    if @loan.save
<<<<<<< HEAD
      redirect_to generate_amortization_schedule_loan_path(@loan)
=======
      redirect_to calculate_amortization_schedule_loan_path(@loan)
>>>>>>> b4be61b0148bdb2901ddfe4f8578c9840eb76389
    else
      render :new
    end
  end

<<<<<<< HEAD
  def generate_amortization_schedule
=======
  def calculate_amortization_schedule
>>>>>>> b4be61b0148bdb2901ddfe4f8578c9840eb76389
    @loan = Loan.find(params[:id])
    @amortization_schedule = @loan.amortization_schedule
  end

  def index
    @loans = Loan.all
  end

  private

  def loan_params
    params.require(:loan).permit(:loan_amount, :monthly, :interest_rate, :request_date, :amortization_type)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/views/layouts/_error_alerts.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
  <div class="alert alert-danger">
    The form contains
    <%= pluralize(object.errors.count, "error") %>.
  </div>
  <ul>
    <% object.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
     <%= link_to "Amortization Schedule Calculator", root_path, class: 'navbar-brand' %>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li class="active"><%= link_to "View all loans", loans_path, class: 'btn btn-info' %></li>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AmortizationSchedule</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class = "container-fluid">
<<<<<<< HEAD
      <%= render partial: "shared/navbar" %>
=======
      <%= render partial: "layouts/navbar" %>
>>>>>>> b4be61b0148bdb2901ddfe4f8578c9840eb76389
      <div class = "flash">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/loans/calculate_amortization_schedule.html.erb
<div class="loan-details">
  <h3>Loan Details</h3>
  <table class="table table-bordered">
    <thead class="thead-inverse">
      <tr>
        <th>Loan Amount</th>
        <th>monthly</th>
        <th>Interest rate</th>
        <th>Requested date</th>
        <th>Amortization type</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @loan.loan_amount %></td>
        <td><%= @loan.monthly %></td>
        <td><%= @loan.interest_rate %></td>
        <td><%= @loan.request_date.strftime("%d %b %Y") %></td>
        <td><%= @loan.amortization_type%></td>
      </tr>
    </tbody>
  </table>
</div>

<div class="amortization-schedule">
  <h3>
    Amortization Schedule of the Loan
  </h3>
  <table class="table table-bordered">
    <thead class="thead-inverse">
      <tr>
        <th>Due Date</th>
        <th>Beginning Balance</th>
        <th>Payment Amount</th>
        <th>Interest Componenet</th>
        <th>Principal Componenet</th>
        <th>Remaining Balance</th>
      </tr>
    </thead>
    <tbody>
      <% @amortization_schedule.each do |entry| %>
        <tr>
          <td><%= entry[:due_date].strftime("%d %b %Y") %></td>
          <td><%= entry[:beginning_balance].round(2) %></td>
          <td><%= entry[:monthly_payment].round(2) %></td>
          <td><%= entry[:interest_component].round(2) %></td>
          <td><%= entry[:principal_component].round(2) %></td>
          <td><%= entry[:ending_balance].round(2) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/loans/generate_amortization_schedule.html.erb
<div class="loan-details">
  <h3>Loan Details</h3>
  <table class="table table-bordered">
    <thead class="thead-inverse">
      <tr>
        <th>Loan Amount</th>
        <th>Monthly</th>
        <th>Interest rate</th>
        <th>Requested date</th>
        <th>Amortization type</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @loan.loan_amount %></td>
        <td><%= @loan.monthly %></td>
        <td><%= @loan.interest_rate %></td>
        <td><%= @loan.request_date.strftime("%d %b %Y") %></td>
        <td><%= @loan.amortization_type%></td>
      </tr>
    </tbody>
  </table>
</div>

<div class="amortization-schedule">
  <h3>
    Amortization Schedule of the Loan
  </h3>
  <table class="table table-bordered">
    <thead class="thead-inverse">
      <tr>
        <th>Due Date</th>
        <th>Beginning Balance</th>
        <th>Payment Amount</th>
        <th>Interest Componenet</th>
        <th>Principal Componenet</th>
        <th>Remaining Balance</th>
      </tr>
    </thead>
    <tbody>
      <% @amortization_schedule.each do |entry| %>
        <tr>
          <td><%= entry[:due_date].strftime("%d %b %Y") %></td>
          <td><%= entry[:beginning_balance].round(2) %></td>
          <td><%= entry[:monthly_payment].round(2) %></td>
          <td><%= entry[:interest_component].round(2) %></td>
          <td><%= entry[:principal_component].round(2) %></td>
          <td><%= entry[:ending_balance].round(2) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/loans/index.html.erb
<div class="loans-table">
  <table class="table table-striped ">
    <thead class="thead-default">
      <tr>
        <th>Loan Amount</th>
        <th>Monthly</th>
        <th>Interest rate</th>
        <th>Requested date</th>
        <th>Loan type</th>
        <th>Loan Schedule</th>
      </tr>
    </thead>
    <tbody>
      <% @loans.each do |loan| %>
      <tr>
        <td><%= loan.loan_amount %></td>
        <td><%= loan.monthly %></td>
        <td><%= loan.interest_rate %></td>
        <td><%= loan.request_date %></td>
        <td><%= loan.amortization_type %></td>
        <td><%= link_to "Get Loan Schedule", calculate_amortization_schedule_loan_path(loan) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/loans/new.html.erb
<h2>
  Amortization Schedule Calculator
</h2><br>
<div class="new-loan-div">
  <div class="new-loan-form">

    <%= form_for @loan do |f| %>
    <%= render 'shared/error_messages', object: @loan  %>
    <%= f.label :loan_amount %><br>
    <%= f.text_field :loan_amount, class: 'form-control' %>

    <%= f.label :monthly %><br>
    <%= f.text_field :monthly, class: 'form-control' %>

    <%= f.label :interest_rate %><br>
    <%= f.text_field :interest_rate, class: 'form-control' %>

    <%= f.label :amortization_type %><br>
    <%= f.select :amortization_type, options_for_select(Loan::VALID_AMORTIZATION_TYPE.each {|type|}), class: 'form-control' %><br>

    <%= f.label :request_date %><br>
    <%=  f.text_field :request_date, class: 'datepicker' %><br>

    <%= f.submit "Generate Amortization schedule", class: "btn btn-primary"  %>

    <% end %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
  <div class="alert alert-danger">
    The form contains
    <%= pluralize(object.errors.count, "error") %>.
  </div>
  <ul>
    <% object.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
<<<<<<< HEAD:app/views/shared/_navbar.html.erb
      <%= link_to "Amortization Schedule Calculator", root_path, class: 'navbar-brand' %>
=======
     <%= link_to "Amortization Schedule Calculator", root_path, class: 'navbar-brand' %>
>>>>>>> b4be61b0148bdb2901ddfe4f8578c9840eb76389:app/views/layouts/_navbar.html.erb
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li class="active"><%= link_to "View all loans", loans_path, class: 'btn btn-info' %></li>
  </div>
</nav>